name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: adhatcher-org/shared-workflows/.github/workflows/app-ci.yml@456f186a9c21632af188bde4ebf7ce6e11953831 # v1.0.2
    with:
      python-version: "3.13"
      dependency-manager: pip
      run-lint: true
      run-typecheck: true
      run-tests: true
      run-coverage: true
      run-security: true
      run-docker-build: true
